### ISSUE TITLE
Getting an error

### ISSUE THREAD

**Issue by FabrizioRolon** [lowyiyiu/League-of-Legends-5v5-Practice-Tool#1]
![imagen_2023-12-12_192125389](https://github.com/lowyiyiu/League-of-Legends-5v5-Practice-Tool/assets/51301428/746c15d0-7e2b-41e4-83f2-c589eff38bb9)

**Comment by lowyiyiu** [comment]
Please download the latest release (v2)

https://github.com/lowyiyiu/League-of-Legends-5v5-Practice-Tool/releases/download/v2/5v5PracticeTool.exe
